### ISSUE TITLE
About minSdkVersion  question.

### ISSUE THREAD

**Issue by DeloDuan** [android10/frodo#10]
My English is not good, I hope you can understand.
this minSdkVersion is 14, but i want turn down 10.
Can you give me some advise to cope with this problem？

**Comment by android10** [comment]
Sorry, you cannot. The library relies on features that are provided by android sdk 14 and up.
Maybe your case is particular but nowadays the number of devices with sdk < 14 is very low and is not worth development effort to support a lower sdk.
