### ISSUE TITLE
Gradle sync error

### ISSUE THREAD

**Issue by dbacinski** [android10/frodo#13]
After bumping plugin version, gradle sync fails on sample app module and I am not able to build library. The same problem occurs while building commit on jitpack.

~~~~
Error:A problem occurred configuring project ':frodo-android-sample'.
> Could not resolve all dependencies for configuration ':frodo-android-sample:classpath'.
   > Could not find com.fernandocejas.frodo:frodo-plugin:0.8.4.
     Searched in the following locations:
         file:/XXX/Android Studio 1.5/gradle/m2repository/com/fernandocejas/frodo/frodo-plugin/0.8.4/frodo-plugin-0.8.4.pom
         file:/XXX/Android Studio 1.5/gradle/m2repository/com/fernandocejas/frodo/frodo-plugin/0.8.4/frodo-plugin-0.8.4.jar
         https://jcenter.bintray.com/com/fernandocejas/frodo/frodo-plugin/0.8.4/frodo-plugin-0.8.4.pom
         https://jcenter.bintray.com/com/fernandocejas/frodo/frodo-plugin/0.8.4/frodo-plugin-0.8.4.jar
         https://repo1.maven.org/maven2/com/fernandocejas/frodo/frodo-plugin/0.8.4/frodo-plugin-0.8.4.pom
         https://repo1.maven.org/maven2/com/fernandocejas/frodo/frodo-plugin/0.8.4/frodo-plugin-0.8.4.jar
         file:/XX/.m2/repository/com/fernandocejas/frodo/frodo-plugin/0.8.4/frodo-plugin-
     Required by:
         com.fernandocejas.frodo:frodo-android-sample:0.8.4
~~~~

https://jitpack.io/com/github/dbacinski/frodo/f87c2c4113/build.log

**Comment by android10** [comment]
have you tried first executing ```./install_frodo``` ? Since every time I rollout a new version I commit changes regarding next development version, which still does not exist.

**Comment by dbacinski** [comment]
Thank you for help, now it works.

After running ./install_frodo and instaling Maven3 project builds correctly. 
Without Maven installed script was not able to install artifact in local maven repository:
~~~~
:frodo-runtime:install FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':frodo-runtime:install'.
> A problem occurred starting process 'command 'mvn''
~~~~
Issue is still valid for jitpack build.

**Comment by android10** [comment]
@dbacinski it relies on maven to install in local repository. For now unfortunately, I will not give support to jitpack, I will open an issue and mark it as enhancement. 

Thanks for your collaboration buddy!
