### ISSUE TITLE
Logging for anonymus subscriber

### ISSUE THREAD

**Issue by iammert** [android10/frodo#15]
I see that we can use RxLogSubscriber annotation for Subscriber classes,Is there any suggestion for anonymus subscriber?

**Comment by android10** [comment]
Can you elaborate a little bit more? What is your use case or problem you are facing?

**Comment by iammert** [comment]
```
      subscription = getRadioListUsecase.getRadioList()
                .subscribe(new Subscriber<RadioWrapper>() {
                    @Override
                    public void onCompleted() {

                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onNext(RadioWrapper radioWrapper) {
                        radioListView.onListLoaded(radioWrapper);
                        radioListView.dismissLoading();
                    }
                });
```

This is snippet from my Presenter class. Can i use RxLogSubscriber on anonymus subscriber?

**Comment by android10** [comment]
@iammert I thought you were meaning when you call ```subscribe()``` without any parameters which internally creates an anonymous ```Subscriber()```. 
Anyway, either case is not possible at the moment with ```frodo```. I will keep it in mind for future versions although I have to investigate a little bit more and I cannot assure that this is doable. 

If you come up with a solutions, I will really appreciate a PR :smile:

**Comment by android10** [comment]
Closing the ticket for now. Thanks for the feedback.
