### ISSUE TITLE
No Logoutput at all

### ISSUE THREAD

**Issue by meierjan** [android10/frodo#2]
Hey,

first thanks for your effort @android10.

I set up a project inspired by your clean-architecture repo (so I am using multi-modules). I (for example) put annotations on the `DefaultSubscriber` class (which is exactly as it is in your c-a repo). The `defaultPublishConfig` is added to all project build.gradle files. Everything compiles fine.

The Problem is that I don't get any output at all. 

Excerpt from the build.gradle:
```[...]
apply plugin: 'com.fernandocejas.frodo'

android {
    defaultPublishConfig "debug"
[...]```

Any ideas why there is no output? (As I don't have errors I can't post them)

**Comment by android10** [comment]
Hi @meierjan, this is the commit where I enabled frodo on the Clean Architecture project. Can you make sure that you added frodo to your classpath in your build script?

https://github.com/android10/Android-CleanArchitecture/commit/0879354b4b5c9afb78d82be0d8cf16bcfd09ad90

**Comment by xk009** [comment]
> android10

I have same question。I config project follow your introduction。

**Comment by meierjan** [comment]
Double checked and everything is the same.

**Comment by android10** [comment]
@meierjan @xk009 is it working for you? Maybe the documentation is not clear or I'm missing something. Please any feedback/input on this is very welcome.

**Comment by meierjan** [comment]
@android10 Yes, it started working magically. I have no clue why - I didn't change anything :+1: Maybe making a clean build did the trick

**Comment by android10** [comment]
@meierjan good to hear. Maybe the android build tools or something that you updated did the trick. Anyway, thanks for the feedback/input :)
