### ISSUE TITLE
Disable Frodo using Gradle

### ISSUE THREAD

**Issue by simplysoft** [android10/frodo#20]
This is related to #19. As an alternative it would be good to have the ability to manually disable frodo, similar as it is possible with [hugo](https://github.com/JakeWharton/hugo), something like this:

```
frodo {
  enabled false
}
```

**Comment by android10** [comment]
Interesting and fair point. Will mark it as enhancement. Thanks for the suggestion.

**Comment by android10** [comment]
This was added here: https://github.com/android10/frodo/commit/d5a910f7e1bea3600aa9a61b560901435b8b3714
