### ISSUE TITLE
App is crashing with NullPointerException on Android 4.2.2

### ISSUE THREAD

**Issue by Coolerfall** [android10/frodo#23]
Caused by: java.lang.NullPointerException at com.fernandocejas.frodo.aspect.LogObservable.methodAnnotatedWithRxLogObservable(LogObservable.java:27)
I just use Observable.just(SomethingList), but sometimes SomethingList will be a empty list(not null), or when I use Observable.empty(), and then it is crashing when use @RxLogObservable.

**Comment by Nexen23** [comment]
Same here. Any workarounds?

**Comment by aleksandar9** [comment]
Hi
You can use the following sample to reproduce the issue:
```
@Override
@RxLogObservable
public Observable<UserBo> getTrainLayout(String userId) {
    UserBo userBo = new UserBo(userId);
    return Observable.just(userBo);
}
```
Also, I can confirm it not only crashes on Android 4.2.2, but also on Android 4.4.2 with the following log:
```
Caused by: java.lang.NullPointerException 
at com.fernandocejas.frodo.aspect.LogObservable.methodAnnotatedWithRxLogObservable(LogObservable.java:27)
```
After some debugging I discovered that LogObservable.java:25  `final Annotation annotation = frodoJoinPoint.getAnnotation(RxLogObservable.class);` is actually null and therefore causing the crash.

**Comment by aleksandar9** [comment]
I see that this issue might be resolved in version 0.8.3, I hope it will be published soon enough ;)

**Comment by paramsen** [comment]
I'm experiencing this as well:
`java.lang.NullPointerException at com.fernandocejas.frodo.aspect.LogObservable.methodAnnotatedWithRxLogObservable(LogObservable.java:27)`

**Comment by android10** [comment]
This was fixed here: https://github.com/android10/frodo/commit/33dea2c4f28c7d4eefc9f9811d23e91fc7c35a01

Releasing a new version next week. Thanks for reporting.

**Comment by dawidhyzy** [comment]
Same issue on Android 4.4.2

**Comment by android10** [comment]
Closing since version 0.8.3 has been released 😃
