### ISSUE TITLE
Logging for methods returning Subscription

### ISSUE THREAD

**Issue by Android-s14** [android10/frodo#3]
Feature request if this is technically possible.

**Comment by android10** [comment]
Could you elaborate more @Android-s14 ?

**Comment by Android-s14** [comment]
My apologies for being unclear.
Say we have a method:
```
Observable<String> changes();
```
I can just annotate it with `@RxLogObservable` and it works great.

Now I decide it's more convenient to subscribe to this observable inside the method and return `Subscription` (e.g., to add it to a `CompositeSubscription` right away):
```
Subscription changes();
```
I can always extract the observable creation part into it's own method and annotate it, but wouldn't it be convenient if I also could annotate methods returning `Subscription`?

**Comment by android10** [comment]
I want to keep the library as simple as possible for now and fix issues people come up with.
Even though that, this is something I will keep in mind for future versions. 
Thanks for the feedback.

**Comment by farmazon3000** [comment]
> I will keep in mind for future version

Then why did you close this issue instead of changing it to "feature request" type?
